### ISSUE TITLE
[Feature Request] Support for Dactyl Manuform 5x6

### ISSUE THREAD

**Issue by smoralesd** [manna-harbour/qmk_firmware#14]
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Currently, there is support for the Dactyl Manuform 4x5. I tried flashing my DM 5x6, which technically works but the keys are all over the place (or missing). I'm guessing the subset mapping in the `config.h` file is just not compatible with the 5x6.

**Comment by manna-harbour** [comment]
Yes, it will need a new subset mapping.  I will add one, but it might be a week or so before I can get to it.  If you'd like to try making one yourself in the mean time please see the customisation section of the docs.

**Comment by smoralesd** [comment]
Hi @manna-harbour I ended up trying to follow this commit: [Add dactyl_manuform/4x5](https://github.com/manna-harbour/qmk_firmware/commit/e869a5e1e29976ae47975053fbc6797281b7c765), since it's also a dactyl manuform layout.

I created this commit: [WIP add miryoku keymap for dactyl manuform 5x6](https://github.com/manna-harbour/qmk_firmware/commit/e869a5e1e29976ae47975053fbc6797281b7c765). 

Then, I run the following command `qmk compile -kb handwired/dactyl_manuform/5x6 -km miryoku` but I'm getting this error:
```bash
Ψ Compiling keymap with make handwired/dactyl_manuform/5x6:miryoku


QMK Firmware 0.10.1
Making handwired/dactyl_manuform/5x6 with keymap miryoku

avr-gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: tmk_core/common/command.c                                                                [OK]
Linking: .build/handwired_dactyl_manuform_5x6_miryoku.elf                                           [ERRORS]
 |
 | .build/obj_handwired_dactyl_manuform_5x6_miryoku/quantum/keymap_common.o: In function `keymap_key_to_keycode':
 | /home/<user>/qmk_firmware/quantum/keymap_common.c:182: undefined reference to `keymaps'
 | /home/<user>/qmk_firmware/quantum/keymap_common.c:182: undefined reference to `keymaps'
 | collect2: error: ld returned 1 exit status
 |
make[1]: *** [tmk_core/rules.mk:306: .build/handwired_dactyl_manuform_5x6_miryoku.elf] Error 1
Make finished with errors
make: *** [Makefile:584: handwired/dactyl_manuform/5x6:miryoku] Error 1
```
I'm not sure where to follow from there.

Other details I can share:
- I'm using WSL on Windows 10
- I'm able to compile other (already existing) firmware 
- I also tried `make handwired/dactyl_manuform/5x6:miryoku` but that gets me the same error.

Any guidance you can share with me?

**Comment by manna-harbour** [comment]
I can't see your code as you've used the wrong link, but for your config.h it will need to be based on .../keyboards/handwired/dactyl_manuform/5x6/5x6.h. Compare that with 4x5.h and the corresponding subset mapping config.h.

**Comment by smoralesd** [comment]
My bad. This is the right [link](https://github.com/smoralesd/qmk_firmware/commit/4e41ba601e34e0a2bd9a50198d112b0ccc290da5). I also edited the original comment.

I did look at the file you mentioned to come up with my changes. I'll have a second look.

**Comment by manna-harbour** [comment]
What you've done looks good! I don't have access to my system at the moment so I can't test it.  Please try to build miryoku for another keyboard to try to narrow down the problem.

**Comment by manna-harbour** [comment]
The directory needs to be named `manna-harbour_miryoku` rather than just `miryoku` as it needs to match the userspace directory name where the actual keymap is located.  This keyboard has been added now.
