### ISSUE TITLE
[Feature Request] Custom NAVR layer (vi compatible)

### ISSUE THREAD

**Issue by ordnungswidrig** [manna-harbour/qmk_firmware#2]
Is there a simple way to add a variation to the NAVR layer like with the base layers? I'd prefer VI style mapping of the arrow keys (to HJKL).

**Comment by manna-harbour** [comment]
Thanks for the suggestion!

I suppose the next row down (HOME PGDN PGUP END) should move across too, and the corresponding rows in MOUR and MEDR.

I'll add it soon.

**Comment by manna-harbour** [comment]
It's in the testing branch now.  Let me know what you think.

https://github.com/manna-harbour/qmk_firmware/blob/miryoku-testing/users/manna-harbour_miryoku/miryoku.org#vi-style-navigation

https://github.com/manna-harbour/qmk_firmware/compare/miryoku...manna-harbour:miryoku-testing
