### ISSUE TITLE
[Bug] Can't leave Capslock

### ISSUE THREAD

**Issue by thecatwasnot** [manna-harbour/qmk_firmware#21]
## Describe the Bug
I'm using the latest miryoku branch on an ErgoDox Infinity with Qwerty layout and VI style navigation, when capslock mode is entered it seems the only way to get out of it is to reboot the computer.  I'd be happy to disable capslock entirely as I never use it. 

## System Information

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system:
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version:

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by manna-harbour** [comment]
If you press caps lock it turns on, but if you press it again it doesn't turn off? There's nothing special about the caps lock in this keymap, it's just the standard QMK keycode. Can you try this keyboard on a different computer, and try a different keyboard (or keymap) on this computer, and test the caps lock behaviour?

**Comment by manna-harbour** [comment]
Let me know if this is still an issue.
