### ISSUE TITLE
[Feature Request] bilateral combinations per key setting

### ISSUE THREAD

**Issue by urob** [manna-harbour/qmk_firmware#26]
A `bilateral_combinations_per_key` setting for the bilateral combinations option could be a useful feature.

## Description

The setting would determine which tab-mods would be affected by the bilateral combinations setting and would work similar to `permissive_hold_per_key`. The setting would be useful to allow for certain one-handed combinations, while restricting home row mods to opposite hands. E.g., one could enable one-handed short-cuts involving thumb mods, which would be useful when when having one hand on the keyboard and the other one on the mouse

**Comment by manna-harbour** [comment]
Thanks for the suggestion.  This will be included in the next implementation.  See #29.

One-handed combinations are currently possible with a timeout:

> If `BILATERAL_COMBINATIONS` is defined to a value, hold times greater than that value will permit same hand combinations.

**Comment by manna-harbour** [comment]
See https://github.com/manna-harbour/qmk_firmware/issues/42.
