### ISSUE TITLE
[Feature Request] Disable a few mod keys

### ISSUE THREAD

**Issue by gmelodie** [manna-harbour/qmk_firmware#41]
It would be awesome to be possible to disable a few modifiers from the Bilateral Combinations setup. I want to do Ctrl+C, Ctrl+V or Ctrl+R with the same hand (e.g. `LCTL_T(KC_Z)` + `KC_C`) because I'm very used to doing this with the same hand and I always end up with "zc", "zv" since my Ctrl mod is on Z.

**Comment by manna-harbour** [comment]
See https://github.com/manna-harbour/qmk_firmware/issues/42.
